---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
spec:
  encryptedData:
    database-password: AgBBm/4teORfukOBJLC6W5Zw51vpYkesPbqHzO2lHwV08pOiDO3Z8V0clU4O8LJiThWZkPNDm37aWb8Zevy/ZdQury5KBmqMnHI0IONjqZ9KDQI7yhje884yY07GGRGt3XTQSBIvt4nZmvUdnxWwgfYWrXG4PfygFLj8vYktvcGKA5H/86pWaBCIx3OocCJnsO4vtOc7r/U6w0B3OASrR7lghdq1IPYtflAX9zM50aAspbmRSRoljFSJVrp6BJ0AyO43Pc2XPETOEngf0zldPPU5u2aXtSWCHkSlh/vpDuzvCI9V3PYSFpIXCofeaddTXTjVSMhElANOGMICe2fX6MAloid+lEKzJjto3AUyDKTn64gC92WntyeR336m1rqIpjQERKQ5eNYsZiGpwR4fhjuOof1erJ3/LfUukssF0x+AdShhkCG4bNuETqSxd5ioS4XJSlITG5Gk3ECGL+0TL2WMn3OC36fhFb4HtdaYK3ytDpJtctTkC0+A4G7Xf209jYrjXfFtsakGr7dsS8dAUcOaCfBVvsBHJS0CKtmpyzc5ADydGES4iwjczBMn6X8cg0JrFQseIgKcxewW01IAuMyhGI5pHZRzpkle+ZRoYSj6JSsMWHyV0f6MuN5xeYy2IjuouOijBQRKJdkj0zsskpZugsK8CY/Rj5PSMaVfstjS8M1mu2103rRI4tisIPUDFNXQxLCpIBpXBiAJ
    database-user: AgB3oy1K2BVseSBPmF0K+7LgwUnR+qn7sGGJR+O+rfQneu58qOYVpDqUmJLI84dDBICcKb2D0g1jycwHDw38JxBCXnak0E9TvAnhXYCL0Ni1Y7f/e8z/lDp281kK02CEcBiyqL1agoTE0IVEOsqlP3vAcWZFjeoyHmJyrWl4+oSypfint7R/w6Bu5wRT0FZUc6KuMUgS9kMS6HbPWJ1bZlJS8ieEqbW91wceHM1NsvCL4oytDCygoRWcYlMaFIfTNfrknPjxpAzlWcwD+4M1H8J74/oA+l5lPJbuqddTdf3VRdUqjwQ3l3g+rqtYj89mw/d6oQkZTbcsj4WloFQypO70O1n9q1vOONO9KKclMhDN/N4jfMqBXEb9qeLSW1ny8UsBIxpvLPGw/rfT182MvRO2I0/iaUeOFyycDMknVc3pmCwPRYeeyG/p2eGxdYt1ywLJl78JWBD+EC2ugGGvdrQET4bZpd8GBrHmrggp/hZp96ZFUPvemmkNTX0EcpwQ7eYf9ao2nXPT+Gp1A4FAd4BXYeM3achE6zi5M4rE3oWiOMeddPLbAhDxA48vVRDVkG+GrRFJilm2yUZY8fJq7ugk91oKIySMMOGRxjc5V6CZMFrdOLyJwigOOJXZWMd6lT9oSq5j+TpAiZ3zjqpygDqoQuxD0X6/ry2JfvoL3SAfYZi1EV0BMD4ufXsqHPmLgVKNLNXkrpY5
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
      namespace: todo-dev
    type: Opaque
