apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: todo-java-db
    app.kubernetes.io/name: todo-java-db
    app.openshift.io/runtime: postgresql
  name: todo-java-db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-java-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: todo-java-db
        app.kubernetes.io/name: todo-java-db
        app.kubernetes.io/part-of: todo-java-app
        app.openshift.io/runtime: postgresql
    spec:
      imagePullSecrets:
        - name: image-registry-secret
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: todo-java-db-configmap
                  key: timezone
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todo-java-db-configmap
                  key: database_name
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: todo-java-db-secret
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-java-db-secret
                  key: database-password
          image: registry.redhat.io/rhel8/postgresql-15
          imagePullPolicy: IfNotPresent
          name: todo-java-db
          ports:
            - containerPort: 5432
              name: psql-port
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          securityContext:
            runAsNonRoot: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
