apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app.kubernetes.io/instance: todo-java-app
    app.kubernetes.io/name: todo-java-app
  name: todo-java-route
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: todo-java-svc
    weight: 100
  wildcardPolicy: None