---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
spec:
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
    type: Opaque
